parameters:
  - name: method
    default: ""
    type: string
  - name: quickScan
    displayName: Quick Scan
    type: boolean
    default: false
  - name: uploadResults
    displayName: Upload Results
    type: boolean
    default: false
    
pool:
  vmImage: ubuntu-latest
  #vmImage: 'windows-latest'
  
variables:
- group: 'SCA Agent Configuration' # Reference the library containing Veracode Credentials

jobs:
  - job: SCA_Agent_Security_Testing
    displayName: Software Componsition Analysis Testing

    steps:
    - script: ls -la
    - ${{ if eq(parameters.quickScan, true) }}:
      - script: curl -sSL  https://download.sourceclear.com/ci.sh | sh -s -- scan --url https://github.com/srcclr/example-ruby --no-upload --quick
        displayName: Performing SCA Analysis
    - ${{ if eq(parameters.quickScan, false) }}:
      - script: curl -sSL  https://download.sourceclear.com/ci.sh | sh -s -- scan --url https://github.com/srcclr/example-ruby --no-upload
        displayName: Performing SCA Analysis
