name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none
   # - main
pr: none

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'
